[package]
name = "manteau-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "MJML and plaintext rendering implementation for Manteau."
readme = "README.md"
keywords = ["email", "mjml", "rendering"]
categories = ["email", "template-engine"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
manteau-core.workspace = true
mrml.workspace = true
html2text.workspace = true
thiserror.workspace = true
